image: golang:latest

stages:
  - build

compile:
  stage: build
  script:
    - GOBIN=/usr/local/bin/ go install github.com/packwiz/packwiz@latest
    - packwiz mr export
  artifacts:
    paths:
      - ./*.mrpack
