image: golang:latest

generate:
  script:
    - GOBIN=/usr/local/bin/ go install github.com/packwiz/packwiz@latest
    - cd packwiz
    - packwiz mr export
    - packwiz cf export
  artifacts:
    paths:
      - ./packwiz/*.mrpack
      - ./packwiz/*.zip
