image: golang:latest

stages:
  - prepare
  - build
  - deploy

format:
  stage: prepare
  script:
    - go install github.com/packwiz/packwiz@latest

compile:
  stage: build
  script:
    - packwiz mr export
  artifacts:
    paths:
      - ./*.mrpack
