image: golang:latest

stages:
  - build

compile:
  stage: build
  script:
    - GOBIN=/usr/local/bin/ go install github.com/packwiz/packwiz@latest
    - cd packwiz
    - packwiz mr export
    - packwiz cf export
  artifacts:
    paths:
      - ./packwiz/*.mrpack
      - ./packwiz/*.zip
