image: golang:latest

stages:
  - prepare
  - build

prepare:
  stage: prepare
  script:
    - GOBIN=$HOME/.local/bin go install github.com/packwiz/packwiz@latest

compile:
  stage: build
  script:
    - packwiz mr export
  artifacts:
    paths:
      - ./*.mrpack
