name = "OriginCode's VanillaEnhanced"
author = "OriginCode"
version = "1.18_20220612"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d6ea3463d37582aa68d65c278527efd7b7890be5465ceacdc9877f2da0ef8fd"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
