name = "OriginCode's VanillaEnhanced"
author = "OriginCode"
version = "1.18_20220610"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fab86be064ac749666397bd78aefa6bf5e5a6c51a4519902d617d23c85bf35b"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
