name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20221009"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ec06a8bf01dbdc9ed54ba0654f1cbbeefbc1358615419472d3c67735332d58b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
