name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220720-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c7fe6270544bab9f5a5b851b23e4e332eb572285d049ba1e27d2865bf2bbf17"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
