name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220820"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05f3cac6666d9851d206026321a1ec3e98a81e4509557eeee800d5b0354c4e00"

[versions]
minecraft = "1.19"
quilt = "0.17.3"

[options]
acceptable-game-versions = ["1.19"]
