name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20240101"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c994648d9b86b33d5b8c41c26de8cb809b335e881a9337855aef214a0292bc"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
