name = "OriginCode's VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220712"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5daaaee2fa724fb1c891741a28c0d31d913d6a78b526d82f8acdb471f428c5a"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
