name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20240210"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9479c22fe4370e2753a7e0367425b1264411a5e98cc6388f873850197ae6854c"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
