name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220801"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af371d278c617e56eb1a3b636fb48bda5f0c4808246b02a6c67a2113e9ae3196"

[versions]
minecraft = "1.19"
quilt = "0.17.1"

[options]
acceptable-game-versions = ["1.19"]
