name = "VanillaEnhanced"
author = "OriginCode"
version = "1.21.1-20260120"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5da4bd290a9a56dc38ed929d151e6a916d0bf56a2b5516918cf0193d4200e40"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
