name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20231202"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19248c6096ea2c3ced82ddb22522a8450da3f2b2335345aa900a3c26e44e53de"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
