name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20221015"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30a094a5368c6f270d7681062418b8c69fc8fa93d5d52be2c66ad2fe4987cf5e"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
