name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20231122"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85973b1151abf592df8006ac24fa8bede28cda09fe0a0a275c6e2307a6f4635d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
