name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20230120"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3917e452950b11b07bbd3f9e2e6fc63cf48bd3aeefbe2c445e19189f44dcd8b4"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"

[options]
acceptable-game-versions = ["1.19.2"]
