name = "VanillaEnhanced"
author = "OriginCode"
version = "1.21.1-20250804"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edccdf457794955c8150ab64636963ca281273275e47375675de9bbd5154f083"

[versions]
fabric = "0.17.0"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
