name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20231023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff7b17aa88277719c95d6fd13e8a05d0f48d5ecc324e71a8bd5fa876dd3151b8"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
