name = "VanillaEnhanced"
author = "OriginCode"
version = "1.21.1-20250421"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c09ee6ff69b1245e2f294e81d002977f8deaf82b08ca8fdf9ccaedc52e2b3a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
