name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20230506"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff7625932fc9d7c7fd90e807c32a0f716915de98dce93dd2283232181b143584"

[versions]
minecraft = "1.19.2"
quilt = "0.18.9"

[options]
acceptable-game-versions = ["1.19.2"]
