name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.4-20230513"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1fa61b027bc78574fe119dd98e3586e414371d730ed6e6dde2920d4645586d3"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19.4"]
