name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20230605"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e549e18433efdf90baa05ee363467ed2bb20c84715e40bfb5867a3789c974e6"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19.2"]
