name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220723"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70027e40148717c26d82bbaca927fe2d249b8cda0a71ce93ea080803a39de5ad"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
