name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20230822"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6616dbbf94d3bcf06034f4fd57a7d3630733f7459f603fa51631c6610f59dc9d"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
