name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20231003"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a02d6a26799237bf21b294e6c3ba262c62383aab576073712a891320d495c18"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
