name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20230922"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c921a59a287cb289edded00af2c27caae0d7a71259468d724904c41801ac567"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
