name = "OriginCode's VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220705"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "536e265680c2c9f95d2357b27f26a792f8798f72a4462b820d911d3e90d9cad6"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
