name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20221115"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec7cae72a66ece4fd8b0af8027713ad1e1cc7aa60eb6ca665928cfa474bf7d92"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
