name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220727"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0413ac35aaf4045405238bbe2705055ef2e07ba7b6f4a46d36e9f6e17323e3cc"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
