name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20240327"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38afea72ae084479f652f2df192b0f9d7347992c08e91a52a517e1d4e2d15c6b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
