name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220723-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35a6dc40187214d50e75c3d97b2e49c4a22337d2cfd91ba2addf2b88569f5bdb"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
