name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20231220"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3777484748ca2d9cefc3346d1ec8024f28add12ddc0faed2719f5dd4f33fef0"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
