name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20221023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04ed0c0e243166d8e46b39f5c008d71f6549a625f7531c344ccf06649eb0da2a"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
