name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_20220720"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d160f8bb7da148fc1c3991f0cb3864a415a6581d852749e00b5053af49fe7ffc"

[versions]
minecraft = "1.19"
quilt = "0.17.0"

[options]
acceptable-game-versions = ["1.19"]
