name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20240220"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19928ebdaeea0cb58029caa3375f8443a7542ad0aad9759d0e8db26634373deb"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
