name = "VanillaEnhanced"
author = "OriginCode"
version = "1.20.1-20240108"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6707a36c5e64bd21546f275e7e1d140e85512a79daa4397d5d7a3d93cc9eccc"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
