name = "VanillaEnhanced"
author = "OriginCode"
version = "1.19_1.19.2-20230415"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7de70b128dbb655699a005b9920f5d49f0bb8ace26b68f619f7fd7f46dd49e64"

[versions]
minecraft = "1.19.2"
quilt = "0.18.9"

[options]
acceptable-game-versions = ["1.19.2"]
